### ISSUE TITLE
Invalid API - {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action}

### ISSUE THREAD

**Issue by lucky-ali** [fman42/FutureBinanceAPI#1]
Hello,

When running the code i am getting the following errors, can you help? 

![image](https://user-images.githubusercontent.com/20534354/90077745-d7e0f380-dcfa-11ea-84d3-970db9fddc27.png)

![image](https://user-images.githubusercontent.com/20534354/90077802-fe9f2a00-dcfa-11ea-8bb0-e412588ef7ed.png)

**Comment by fman42** [comment]
Hello!

Yes. I see you use a debug mode(third parameter in **AuthClient()**). Are you sure that APIKey and SecretKey from testnet?(https://testnet.binancefuture.com/).

Debug mode made for testnet. If you use keys from main exchange(https://www.binance.com/en/futures/BTCUSDT) then you need write "false" in debug mode or just ignore that parametr

For example
``
AuthClient client = new AuthClient("api_key", "secret_key"); // for main exchange
``
``
AuthClient testnetClient = new AuthClient("api_key", "secret_key", true); // for testnet exchange
``

**Comment by lucky-ali** [comment]
oh that makes sense now. I was using live credentails and now removed the debug flag and its working as expected. 

Ill close this, thank a bunch for your prompt reply. 

Ill open another issue as i need more information regarding streaming my account trades.
