### ISSUE TITLE
Stream Account information 

### ISSUE THREAD

**Issue by lucky-ali** [fman42/FutureBinanceAPI#2]
Hello, 

How do i achieve and stream the following function:
(i bascailly want to stream everything that is happening on my account in terms of trades)

1. Opening a Trade (Limit, Market) 
2. Closing a Trade (Limit, TakeProfit) 

I tried using the following code i am not sure where i am going wrong. 

![image](https://user-images.githubusercontent.com/20534354/90081311-e9c79400-dd04-11ea-97c5-81ac1268b87a.png)

**Comment by fman42** [comment]
Yep, there is a bug in StreamClient. It will be fix
In this moment it can use in only debug mode(testnet)

Thanks you

**Comment by lucky-ali** [comment]
Is the bug with Binance?

**Comment by fman42** [comment]
No. I didn't see an url of web socket for main exchange. I'll publish new version the library with fixes

**Comment by fman42** [comment]
@lucky-ali , could you check this case? 

``
StreamClient sclient = new StreamClient(listenKey, "wss://fstream.binance.com");
``

**Comment by lucky-ali** [comment]
Hello, 

i added the information and am i now getting this 

![image](https://user-images.githubusercontent.com/20534354/90139577-79565c80-dd70-11ea-9516-b7998827ac50.png)


Code:
![image](https://user-images.githubusercontent.com/20534354/90139677-95f29480-dd70-11ea-9630-929936b4bfff.png)

**Comment by fman42** [comment]
Okey, I tried find the bug and now I have a possible solution

Replace **wss://fstream.binance.com** on **wss://fstream.binance.com/ws** in StreamClient and could you tell me: do you get any errors?

**Comment by lucky-ali** [comment]
hello, 

i have made the changes but now i am getting this new error. 

![image](https://user-images.githubusercontent.com/20534354/90199860-c583ba00-ddcd-11ea-8ed6-d2cce4a9c086.png)

**Comment by fman42** [comment]
Please make full screen of code

**Comment by lucky-ali** [comment]
![image](https://user-images.githubusercontent.com/20534354/90200727-afc3c400-ddd0-11ea-87c0-7bd1c6b25ed9.png)

**Comment by fman42** [comment]
Fixed. Try update the package in nuget (FutureBinanceAPI **2.1.1**) and repeat these actions

Note:
In new version you can create StreamClient like that:
``
StreamClient sclient = new StreamClient(listenKey);
``

**Comment by fman42** [comment]
@lucky-ali , did you check new version of library?
