### ISSUE TITLE
How can I get the balance of my future account?

### ISSUE THREAD

**Issue by mircofx** [fman42/FutureBinanceAPI#4]
Hi, how can I found my future account balance and the one available for positions?

**Comment by fman42** [comment]
Hi. You need use an endpoint "AccountEndPoint". For example:

``
AccountEndPoint endpoint = new AccountEndPoint(your client object);
var account = await endpoint.GetAsync();
``

Variable **account** allows you to get account balance(property Assets) and positions(property "Positions")

**Comment by mircofx** [comment]
Thank you I solved using this code with your help:
`AccountEndPoint endPoint = new AccountEndPoint(client);
var account = await endPoint.GetAsync();
var ids = account.Assets.ToList();
var result = ids.Find(x => x.AssetName.ToString() == "USDT");
  
quantity = Convert.ToDouble(result.WalletBalance.ToString());`
