### ISSUE TITLE
How can i use FutureBinanceAPI in my  framwork project?

### ISSUE THREAD

**Issue by SayidJafari** [fman42/FutureBinanceAPI#7]
Hi dear Milan
I am new to programming and I don't know how I can do that is that possible or no?
is there possible  we use your dll in our network fram work project ?

**Comment by fman42** [comment]
Hi, SayidJafari!

You can get this library by nuget in Visual Studio(for example). Nuget will install automatically all dependencies in your project

I don't recommend use simple .dll file, because you will don't have the possibility to get updates

**Comment by SayidJafari** [comment]
also, installing from Nuget not work with the network framework project? because your API is .net

**Comment by fman42** [comment]
I don't understand what you want to do. Do you want to install the library in a different system, not in .NET?

**Comment by SayidJafari** [comment]
yes, I want to use that in network framework is that possible?

**Comment by fman42** [comment]
For .NET Core 3.1

**Comment by SayidJafari** [comment]
No for the framework is that possible?

**Comment by fman42** [comment]
No
